name: 'sfdx-Techi-Stack'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       working-directory : "./sf-apex"

    steps:
      - uses: actions/checkout@v2              
      - name: Write the token into a file
      
        run: 'echo ${{ secrets.DEVHUB_TOKEN}} > token.txt'
      #- name: Change working dir
       # run: 'cd /home/runner/work/Salesforce-Apex-Recipes/Salesforce-Apex-Recipes/sf-apex'
      - name: Print Current Dir
        run: 'pwd'   
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f token.txt -a DevHub -d'
      - name: Create scratch org
        run: 'sfdx force:org:create -f config/project-scratch-def.json --setalias my-scratch'
        working-directory : "./sf-apex"
      - name: List orgs
        run: 'sfdx force:org:list'
        working-directory : "./sf-apex"
      - name: Push source
        run: 'sfdx force:source:push -u my-scratch'
        working-directory : "./sf-apex"
    
      - name: Run tests
        run: 'sfdx force:apex:test:run -u my-scratch --resultformat human'
      - name: Delete scratch org
        run: 'sfdx force:org:delete -u my-scratch --noprompt'
        working-directory : "./sf-apex"
